---
bind_statistics_channels: true
bind_statistics_allow:
  - any
bind_zone_dir: /var/local/named-zones
bind_zone_file_mode: '0660'
bind_allow_query:
  - any
bind_listen_ipv4:
  - any
bind_listen_ipv6:
  - any
bind_acls:
  - name: acl1
    match_list:
      - 10.11.0.0/16
bind_forwarders:
  - '8.8.8.8'
  - '8.8.4.4'
bind_recursion: true
bind_dns64: true
#bind_query_log: 'data/query.log'
dns_log_dir: "/var/log/named"
bind_log: "{{ dns_log_dir }}/bing.log"

bind_other_logs:
  - file: "{{ dns_log_dir }}/update.log"
    size: 100k
    name: update
    versions: 3
  - file: "{{ dns_log_dir }}/plop/security.log"
    size: 100k
    name: security
    versions: 3
  
bind_query_log:
  file: "{{ dns_log_dir }}/query.log"
  versions: 3
  size: 5m


bind_check_names: 'master ignore'
bind_zone_minimum_ttl: "2D"
bind_zone_ttl: "2W"
bind_zone_time_to_refresh: "2D"
bind_zone_time_to_retry: "2H"
bind_zone_time_to_expire: "2W"
bind_statistics_host: "{{ ansible_default_ipv4.address }}"
